apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: shared-gateway
  namespace: gateway
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: smartmeal
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      metallb.io/loadBalancerIPs: "10.20.20.15"
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All