apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smartmeal
resources:
  - network-policy.yaml
  - gateway.yaml
  - ../../base/api
  - ../../base/predict

patches:
  - path: deployment.yaml
  - path: routing.yaml