// <auto-generated />
using System;
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260529103547_AddIngredientTagFields")]
    partial class AddIngredientTagFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BusinessObject.Entities.Account", b =>
                {
                    b.Property<Guid>("Account_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("Role_id")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Account_id");

                    b.HasIndex("Role_id");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("BusinessObject.Entities.AffiliateProduct", b =>
                {
                    b.Property<Guid>("Product_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Ingredient_id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Partner_id")
                        .HasColumnType("uuid");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Product_id");

                    b.HasIndex("Ingredient_id");

                    b.HasIndex("Partner_id");

                    b.ToTable("AffiliateProducts");
                });

            modelBuilder.Entity("BusinessObject.Entities.Allergy", b =>
                {
                    b.Property<Guid>("Allergy_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Account_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Ingredient_id")
                        .HasColumnType("uuid");

                    b.HasKey("Allergy_id");

                    b.HasIndex("Account_id");

                    b.HasIndex("Ingredient_id");

                    b.ToTable("Allergy");
                });

            modelBuilder.Entity("BusinessObject.Entities.Collection", b =>
                {
                    b.Property<Guid>("Collection_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Account_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Collection_id");

                    b.HasIndex("Account_id");

                    b.ToTable("Collection");
                });

            modelBuilder.Entity("BusinessObject.Entities.Comment", b =>
                {
                    b.Property<Guid>("Comment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Account_id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ParentCommentComment_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Post_id")
                        .HasColumnType("uuid");

                    b.HasKey("Comment_id");

                    b.HasIndex("Account_id");

                    b.HasIndex("ParentCommentComment_id");

                    b.HasIndex("Post_id");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("BusinessObject.Entities.GroceryItem", b =>
                {
                    b.Property<Guid>("Item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Ingredient_id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPurchased")
                        .HasColumnType("boolean");

                    b.Property<Guid>("List_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Product_id")
                        .HasColumnType("uuid");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Item_id");

                    b.HasIndex("Ingredient_id");

                    b.HasIndex("List_id");

                    b.HasIndex("Product_id");

                    b.ToTable("GroceryItems");
                });

            modelBuilder.Entity("BusinessObject.Entities.GroceryList", b =>
                {
                    b.Property<Guid>("List_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Account_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("List_id");

                    b.HasIndex("Account_id");

                    b.ToTable("GroceryLists");
                });

            modelBuilder.Entity("BusinessObject.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Ingredient_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AveragePrice")
                        .HasColumnType("double precision");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Ingredient_id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("BusinessObject.Entities.IngredientLabel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Ingredient_id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("It_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Ingredient_id");

                    b.HasIndex("It_id");

                    b.ToTable("IngredientLabels");
                });

            modelBuilder.Entity("BusinessObject.Entities.IngredientTag", b =>
                {
                    b.Property<Guid>("It_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("It_id");

                    b.ToTable("IngredientTags");
                });

            modelBuilder.Entity("BusinessObject.Entities.NutritionalValue", b =>
                {
                    b.Property<Guid>("Nv_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Calories")
                        .HasColumnType("double precision");

                    b.Property<Guid>("Ingredient_id")
                        .HasColumnType("uuid");

                    b.HasKey("Nv_id");

                    b.HasIndex("Ingredient_id")
                        .IsUnique();

                    b.ToTable("NutritionalValues");
                });

            modelBuilder.Entity("BusinessObject.Entities.Pantry", b =>
                {
                    b.Property<Guid>("Pantry_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Account_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Ingredient_id")
                        .HasColumnType("uuid");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Pantry_id");

                    b.HasIndex("Account_id");

                    b.HasIndex("Ingredient_id");

                    b.ToTable("Pantries");
                });

            modelBuilder.Entity("BusinessObject.Entities.Partner", b =>
                {
                    b.Property<Guid>("Partner_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Partner_id");

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("BusinessObject.Entities.Plan", b =>
                {
                    b.Property<Guid>("Plan_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Plan_id");

                    b.ToTable("Plan");
                });

            modelBuilder.Entity("BusinessObject.Entities.Post", b =>
                {
                    b.Property<Guid>("Post_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Account_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("Recipe_id")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Post_id");

                    b.HasIndex("Account_id");

                    b.HasIndex("Recipe_id");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("BusinessObject.Entities.Rating", b =>
                {
                    b.Property<Guid>("Rating_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Account_id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("RatingValue")
                        .HasColumnType("numeric")
                        .HasColumnName("Rating");

                    b.Property<Guid>("Recipe_id")
                        .HasColumnType("uuid");

                    b.Property<string>("Review")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Rating_id");

                    b.HasIndex("Account_id");

                    b.HasIndex("Recipe_id");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("BusinessObject.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Recipe_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Account_id")
                        .HasColumnType("uuid");

                    b.Property<int>("CookTime")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<int>("PrepTime")
                        .HasColumnType("integer");

                    b.Property<string>("Recipe_name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Servings")
                        .HasColumnType("integer");

                    b.HasKey("Recipe_id");

                    b.HasIndex("Account_id");

                    b.ToTable("Recipe");
                });

            modelBuilder.Entity("BusinessObject.Entities.RecipeIngredient", b =>
                {
                    b.Property<Guid>("RI_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Ingredient_id")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("Recipe_id")
                        .HasColumnType("uuid");

                    b.Property<string>("UOM")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RI_id");

                    b.HasIndex("Ingredient_id");

                    b.HasIndex("Recipe_id");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("BusinessObject.Entities.RecipeLabel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Recipe_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Rt_Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Recipe_Id");

                    b.HasIndex("Rt_Id");

                    b.ToTable("RecipeLabel");
                });

            modelBuilder.Entity("BusinessObject.Entities.RecipeTag", b =>
                {
                    b.Property<Guid>("Rt_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Rt_Id");

                    b.ToTable("Recipe_tag");
                });

            modelBuilder.Entity("BusinessObject.Entities.Report", b =>
                {
                    b.Property<Guid>("Report_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Account_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Comment_id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Post_id")
                        .HasColumnType("uuid");

                    b.HasKey("Report_id");

                    b.HasIndex("Account_id");

                    b.HasIndex("Comment_id");

                    b.HasIndex("Post_id");

                    b.ToTable("Report");
                });

            modelBuilder.Entity("BusinessObject.Entities.Role", b =>
                {
                    b.Property<Guid>("Role_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Role_id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("BusinessObject.Entities.SavedRecipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Account_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Collection_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Recipe_Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Account_id");

                    b.HasIndex("Collection_Id");

                    b.HasIndex("Recipe_Id");

                    b.ToTable("SavedRecipe");
                });

            modelBuilder.Entity("BusinessObject.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Sub_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Account_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentRef")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("Plan_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Sub_id");

                    b.HasIndex("Account_id");

                    b.HasIndex("Plan_id");

                    b.ToTable("Subscription");
                });

            modelBuilder.Entity("BusinessObject.Entities.UserInformation", b =>
                {
                    b.Property<Guid>("User_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Account_id")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("User_id");

                    b.HasIndex("Account_id")
                        .IsUnique();

                    b.ToTable("UserInformation");
                });

            modelBuilder.Entity("BusinessObject.Entities.Account", b =>
                {
                    b.HasOne("BusinessObject.Entities.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("Role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BusinessObject.Entities.AffiliateProduct", b =>
                {
                    b.HasOne("BusinessObject.Entities.Ingredient", "Ingredient")
                        .WithMany("AffiliateProducts")
                        .HasForeignKey("Ingredient_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Entities.Partner", "Partner")
                        .WithMany("AffiliateProducts")
                        .HasForeignKey("Partner_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("BusinessObject.Entities.Allergy", b =>
                {
                    b.HasOne("BusinessObject.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("Account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Entities.Ingredient", "Ingredient")
                        .WithMany("Allergy")
                        .HasForeignKey("Ingredient_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("BusinessObject.Entities.Collection", b =>
                {
                    b.HasOne("BusinessObject.Entities.Account", "Account")
                        .WithMany("Collections")
                        .HasForeignKey("Account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BusinessObject.Entities.Comment", b =>
                {
                    b.HasOne("BusinessObject.Entities.Account", "Account")
                        .WithMany("Comments")
                        .HasForeignKey("Account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Entities.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentComment_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("Post_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("ParentComment");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("BusinessObject.Entities.GroceryItem", b =>
                {
                    b.HasOne("BusinessObject.Entities.Ingredient", "Ingredient")
                        .WithMany("GroceryItems")
                        .HasForeignKey("Ingredient_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Entities.GroceryList", "GroceryList")
                        .WithMany("GroceryItems")
                        .HasForeignKey("List_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Entities.AffiliateProduct", "AffiliateProduct")
                        .WithMany("GroceryItems")
                        .HasForeignKey("Product_id");

                    b.Navigation("AffiliateProduct");

                    b.Navigation("GroceryList");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("BusinessObject.Entities.GroceryList", b =>
                {
                    b.HasOne("BusinessObject.Entities.Account", "Account")
                        .WithMany("GroceryLists")
                        .HasForeignKey("Account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BusinessObject.Entities.IngredientLabel", b =>
                {
                    b.HasOne("BusinessObject.Entities.Ingredient", "Ingredient")
                        .WithMany("IngredientLabels")
                        .HasForeignKey("Ingredient_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Entities.IngredientTag", "Ingredient_tag")
                        .WithMany("IngredientLabels")
                        .HasForeignKey("It_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Ingredient_tag");
                });

            modelBuilder.Entity("BusinessObject.Entities.NutritionalValue", b =>
                {
                    b.HasOne("BusinessObject.Entities.Ingredient", "Ingredient")
                        .WithOne("Nutritional_value")
                        .HasForeignKey("BusinessObject.Entities.NutritionalValue", "Ingredient_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("BusinessObject.Entities.Pantry", b =>
                {
                    b.HasOne("BusinessObject.Entities.Account", "Account")
                        .WithMany("Pantries")
                        .HasForeignKey("Account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Entities.Ingredient", "Ingredient")
                        .WithMany("Pantries")
                        .HasForeignKey("Ingredient_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("BusinessObject.Entities.Post", b =>
                {
                    b.HasOne("BusinessObject.Entities.Account", "Account")
                        .WithMany("Posts")
                        .HasForeignKey("Account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Entities.Recipe", null)
                        .WithMany("Posts")
                        .HasForeignKey("Recipe_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BusinessObject.Entities.Rating", b =>
                {
                    b.HasOne("BusinessObject.Entities.Account", "Account")
                        .WithMany("Ratings")
                        .HasForeignKey("Account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Entities.Recipe", "Recipe")
                        .WithMany("Ratings")
                        .HasForeignKey("Recipe_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("BusinessObject.Entities.Recipe", b =>
                {
                    b.HasOne("BusinessObject.Entities.Account", "Account")
                        .WithMany("Recipes")
                        .HasForeignKey("Account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BusinessObject.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("BusinessObject.Entities.Ingredient", "Ingredient")
                        .WithMany("Recipe_Ingredients")
                        .HasForeignKey("Ingredient_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("Recipe_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("BusinessObject.Entities.RecipeLabel", b =>
                {
                    b.HasOne("BusinessObject.Entities.Recipe", "Recipe")
                        .WithMany("RecipeLabels")
                        .HasForeignKey("Recipe_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Entities.RecipeTag", "RecipeTag")
                        .WithMany("RecipeLabels")
                        .HasForeignKey("Rt_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("RecipeTag");
                });

            modelBuilder.Entity("BusinessObject.Entities.Report", b =>
                {
                    b.HasOne("BusinessObject.Entities.Account", "Account")
                        .WithMany("Reports")
                        .HasForeignKey("Account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Entities.Comment", "Comment")
                        .WithMany("Reports")
                        .HasForeignKey("Comment_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Entities.Post", "Post")
                        .WithMany("Reports")
                        .HasForeignKey("Post_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Comment");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("BusinessObject.Entities.SavedRecipe", b =>
                {
                    b.HasOne("BusinessObject.Entities.Account", null)
                        .WithMany("SavedRecipes")
                        .HasForeignKey("Account_id");

                    b.HasOne("BusinessObject.Entities.Collection", "Collection")
                        .WithMany("SavedRecipes")
                        .HasForeignKey("Collection_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Entities.Recipe", "Recipe")
                        .WithMany("SavedRecipes")
                        .HasForeignKey("Recipe_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("BusinessObject.Entities.Subscription", b =>
                {
                    b.HasOne("BusinessObject.Entities.Account", "Account")
                        .WithMany("Subscriptions")
                        .HasForeignKey("Account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Entities.Plan", "Plan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("Plan_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("BusinessObject.Entities.UserInformation", b =>
                {
                    b.HasOne("BusinessObject.Entities.Account", "Account")
                        .WithOne("UserInformation")
                        .HasForeignKey("BusinessObject.Entities.UserInformation", "Account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BusinessObject.Entities.Account", b =>
                {
                    b.Navigation("Collections");

                    b.Navigation("Comments");

                    b.Navigation("GroceryLists");

                    b.Navigation("Pantries");

                    b.Navigation("Posts");

                    b.Navigation("Ratings");

                    b.Navigation("Recipes");

                    b.Navigation("Reports");

                    b.Navigation("SavedRecipes");

                    b.Navigation("Subscriptions");

                    b.Navigation("UserInformation")
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessObject.Entities.AffiliateProduct", b =>
                {
                    b.Navigation("GroceryItems");
                });

            modelBuilder.Entity("BusinessObject.Entities.Collection", b =>
                {
                    b.Navigation("SavedRecipes");
                });

            modelBuilder.Entity("BusinessObject.Entities.Comment", b =>
                {
                    b.Navigation("Replies");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("BusinessObject.Entities.GroceryList", b =>
                {
                    b.Navigation("GroceryItems");
                });

            modelBuilder.Entity("BusinessObject.Entities.Ingredient", b =>
                {
                    b.Navigation("AffiliateProducts");

                    b.Navigation("Allergy");

                    b.Navigation("GroceryItems");

                    b.Navigation("IngredientLabels");

                    b.Navigation("Nutritional_value")
                        .IsRequired();

                    b.Navigation("Pantries");

                    b.Navigation("Recipe_Ingredients");
                });

            modelBuilder.Entity("BusinessObject.Entities.IngredientTag", b =>
                {
                    b.Navigation("IngredientLabels");
                });

            modelBuilder.Entity("BusinessObject.Entities.Partner", b =>
                {
                    b.Navigation("AffiliateProducts");
                });

            modelBuilder.Entity("BusinessObject.Entities.Plan", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("BusinessObject.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("BusinessObject.Entities.Recipe", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("Ratings");

                    b.Navigation("RecipeLabels");

                    b.Navigation("SavedRecipes");
                });

            modelBuilder.Entity("BusinessObject.Entities.RecipeTag", b =>
                {
                    b.Navigation("RecipeLabels");
                });

            modelBuilder.Entity("BusinessObject.Entities.Role", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
