// <auto-generated />
using System;
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260806072915_FixPlanSubscription")]
    partial class FixPlanSubscription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BusinessObject.Entities.Account", b =>
                {
                    b.Property<Guid>("Account_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Account_id");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("BusinessObject.Entities.AffiliateProduct", b =>
                {
                    b.Property<Guid>("Product_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Ingredient_id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Partner_id")
                        .HasColumnType("uuid");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Product_id");

                    b.HasIndex("Ingredient_id");

                    b.HasIndex("Partner_id");

                    b.ToTable("AffiliateProducts");
                });

            modelBuilder.Entity("BusinessObject.Entities.Allergy", b =>
                {
                    b.Property<Guid>("Allergy_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Account_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Ingredient_id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Allergy_id");

                    b.HasIndex("Account_id");

                    b.HasIndex("Ingredient_id");

                    b.ToTable("Allergies");
                });

            modelBuilder.Entity("BusinessObject.Entities.BmiLog", b =>
                {
                    b.Property<Guid>("Log_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Account_id")
                        .HasColumnType("uuid");

                    b.Property<double?>("Bmi")
                        .HasColumnType("double precision");

                    b.Property<string>("BmiLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double?>("Height")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Log_id");

                    b.HasIndex("Account_id");

                    b.ToTable("BmiLog");
                });

            modelBuilder.Entity("BusinessObject.Entities.Collection", b =>
                {
                    b.Property<Guid>("Collection_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Account_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Collection_id");

                    b.HasIndex("Account_id");

                    b.ToTable("Collection");
                });

            modelBuilder.Entity("BusinessObject.Entities.ConditionDietRecommendation", b =>
                {
                    b.Property<Guid>("Rec_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Condition_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Diet_id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.HasKey("Rec_id");

                    b.HasIndex("Condition_id");

                    b.HasIndex("Diet_id");

                    b.ToTable("ConditionDietRecommendation");
                });

            modelBuilder.Entity("BusinessObject.Entities.DietPlan", b =>
                {
                    b.Property<Guid>("Diet_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<double?>("MaxCarbs")
                        .HasColumnType("double precision");

                    b.Property<double?>("MaxFat")
                        .HasColumnType("double precision");

                    b.Property<double?>("MinProtein")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double?>("TargetCalories")
                        .HasColumnType("double precision");

                    b.HasKey("Diet_id");

                    b.ToTable("DietPlan");
                });

            modelBuilder.Entity("BusinessObject.Entities.GroceryItem", b =>
                {
                    b.Property<Guid>("Item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Ingredient_id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPurchased")
                        .HasColumnType("boolean");

                    b.Property<Guid>("List_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Product_id")
                        .HasColumnType("uuid");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Item_id");

                    b.HasIndex("Ingredient_id");

                    b.HasIndex("List_id");

                    b.HasIndex("Product_id");

                    b.ToTable("GroceryItems");
                });

            modelBuilder.Entity("BusinessObject.Entities.GroceryList", b =>
                {
                    b.Property<Guid>("List_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Account_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("List_id");

                    b.HasIndex("Account_id");

                    b.ToTable("GroceryLists");
                });

            modelBuilder.Entity("BusinessObject.Entities.HealthProfile", b =>
                {
                    b.Property<Guid>("Profile_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Account_id")
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BudgetLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("CookingTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DietType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Goal")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double?>("Height")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("MealsPerDay")
                        .HasColumnType("integer");

                    b.Property<int?>("PlanCycleDays")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetDays")
                        .HasColumnType("integer");

                    b.Property<double?>("TargetWeight")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Profile_id");

                    b.HasIndex("Account_id");

                    b.ToTable("HealthProfile");
                });

            modelBuilder.Entity("BusinessObject.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Ingredient_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AveragePrice")
                        .HasColumnType("double precision");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Ingredient_id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("BusinessObject.Entities.IngredientLabel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Ingredient_id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("It_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Ingredient_id");

                    b.HasIndex("It_id");

                    b.ToTable("IngredientLabels");
                });

            modelBuilder.Entity("BusinessObject.Entities.IngredientTag", b =>
                {
                    b.Property<Guid>("It_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("It_id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("IngredientTags");
                });

            modelBuilder.Entity("BusinessObject.Entities.MealPlan", b =>
                {
                    b.Property<Guid>("MealPlan_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Account_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TotalDays")
                        .HasColumnType("integer");

                    b.HasKey("MealPlan_id");

                    b.HasIndex("Account_id");

                    b.ToTable("MealPlan");
                });

            modelBuilder.Entity("BusinessObject.Entities.MealPlanDay", b =>
                {
                    b.Property<Guid>("Day_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DayDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayIndex")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MealPlan_id")
                        .HasColumnType("uuid");

                    b.HasKey("Day_id");

                    b.HasIndex("MealPlan_id");

                    b.ToTable("MealPlanDay");
                });

            modelBuilder.Entity("BusinessObject.Entities.MealPlanEntry", b =>
                {
                    b.Property<Guid>("Entry_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Day_id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MealSlot")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("Recipe_id")
                        .HasColumnType("uuid");

                    b.Property<double>("SlotCalories")
                        .HasColumnType("double precision");

                    b.Property<double>("SlotCarbs")
                        .HasColumnType("double precision");

                    b.Property<double>("SlotFat")
                        .HasColumnType("double precision");

                    b.Property<double>("SlotFiber")
                        .HasColumnType("double precision");

                    b.Property<double>("SlotProtein")
                        .HasColumnType("double precision");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Entry_id");

                    b.HasIndex("Day_id");

                    b.HasIndex("Recipe_id");

                    b.ToTable("MealPlanEntry");
                });

            modelBuilder.Entity("BusinessObject.Entities.MedicalCondition", b =>
                {
                    b.Property<Guid>("Condition_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Condition_id");

                    b.ToTable("MedicalCondition");
                });

            modelBuilder.Entity("BusinessObject.Entities.NutritionGoal", b =>
                {
                    b.Property<Guid>("Goal_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Account_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<double?>("TargetCalories")
                        .HasColumnType("double precision");

                    b.Property<double?>("TargetCarbs")
                        .HasColumnType("double precision");

                    b.Property<double?>("TargetCholesterol")
                        .HasColumnType("double precision");

                    b.Property<double?>("TargetFat")
                        .HasColumnType("double precision");

                    b.Property<double?>("TargetFiber")
                        .HasColumnType("double precision");

                    b.Property<double?>("TargetProtein")
                        .HasColumnType("double precision");

                    b.Property<double?>("TargetSalt")
                        .HasColumnType("double precision");

                    b.Property<double?>("TargetSugar")
                        .HasColumnType("double precision");

                    b.HasKey("Goal_id");

                    b.HasIndex("Account_id");

                    b.ToTable("NutritionGoal");
                });

            modelBuilder.Entity("BusinessObject.Entities.NutritionLog", b =>
                {
                    b.Property<Guid>("Log_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Account_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Ingredient_id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MealType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double?>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("Recipe_id")
                        .HasColumnType("uuid");

                    b.Property<double?>("TotalCalories")
                        .HasColumnType("double precision");

                    b.Property<double?>("TotalCarbs")
                        .HasColumnType("double precision");

                    b.Property<double?>("TotalCholesterol")
                        .HasColumnType("double precision");

                    b.Property<double?>("TotalFat")
                        .HasColumnType("double precision");

                    b.Property<double?>("TotalFiber")
                        .HasColumnType("double precision");

                    b.Property<double?>("TotalProtein")
                        .HasColumnType("double precision");

                    b.Property<double?>("TotalSalt")
                        .HasColumnType("double precision");

                    b.Property<double?>("TotalSugar")
                        .HasColumnType("double precision");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Log_id");

                    b.HasIndex("Account_id");

                    b.HasIndex("Ingredient_id");

                    b.HasIndex("Recipe_id");

                    b.ToTable("NutritionLog");
                });

            modelBuilder.Entity("BusinessObject.Entities.NutritionalValue", b =>
                {
                    b.Property<Guid>("Nv_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Calories")
                        .HasColumnType("double precision");

                    b.Property<double?>("Carbs")
                        .HasColumnType("double precision");

                    b.Property<double?>("Cholesterol")
                        .HasColumnType("double precision");

                    b.Property<string>("EverydayUnit")
                        .HasColumnType("text");

                    b.Property<double?>("EverydayWeight")
                        .HasColumnType("double precision");

                    b.Property<double?>("Fat")
                        .HasColumnType("double precision");

                    b.Property<double?>("Fiber")
                        .HasColumnType("double precision");

                    b.Property<Guid>("Ingredient_id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<double?>("Protein")
                        .HasColumnType("double precision");

                    b.Property<double?>("Salt")
                        .HasColumnType("double precision");

                    b.Property<double?>("ServingSize")
                        .HasColumnType("double precision");

                    b.Property<string>("ServingUnit")
                        .HasColumnType("text");

                    b.Property<double?>("Sugar")
                        .HasColumnType("double precision");

                    b.HasKey("Nv_id");

                    b.HasIndex("Ingredient_id")
                        .IsUnique();

                    b.ToTable("NutritionalValues");
                });

            modelBuilder.Entity("BusinessObject.Entities.Pantry", b =>
                {
                    b.Property<Guid>("Pantry_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Account_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Ingredient_id")
                        .HasColumnType("uuid");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Pantry_id");

                    b.HasIndex("Account_id");

                    b.HasIndex("Ingredient_id");

                    b.ToTable("Pantries");
                });

            modelBuilder.Entity("BusinessObject.Entities.Partner", b =>
                {
                    b.Property<Guid>("Partner_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Partner_id");

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("BusinessObject.Entities.Plan", b =>
                {
                    b.Property<Guid>("Plan_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasKey("Plan_id");

                    b.ToTable("Plan");
                });

            modelBuilder.Entity("BusinessObject.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Recipe_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Account_id")
                        .HasColumnType("uuid");

                    b.Property<int>("CookTime")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<int>("PrepTime")
                        .HasColumnType("integer");

                    b.Property<string>("Recipe_name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Servings")
                        .HasColumnType("integer");

                    b.HasKey("Recipe_id");

                    b.HasIndex("Account_id");

                    b.ToTable("Recipe");
                });

            modelBuilder.Entity("BusinessObject.Entities.RecipeIngredient", b =>
                {
                    b.Property<Guid>("RI_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Ingredient_id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("Recipe_id")
                        .HasColumnType("uuid");

                    b.Property<string>("UOM")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RI_id");

                    b.HasIndex("Ingredient_id");

                    b.HasIndex("Recipe_id");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("BusinessObject.Entities.RecipeLabel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("Recipe_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Rt_Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Recipe_Id");

                    b.HasIndex("Rt_Id");

                    b.ToTable("RecipeLabel");
                });

            modelBuilder.Entity("BusinessObject.Entities.RecipeTag", b =>
                {
                    b.Property<Guid>("Rt_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Rt_Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Recipe_tag");
                });

            modelBuilder.Entity("BusinessObject.Entities.SavedRecipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Account_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Collection_Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("Recipe_Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Account_id");

                    b.HasIndex("Collection_Id");

                    b.HasIndex("Recipe_Id");

                    b.ToTable("SavedRecipe");
                });

            modelBuilder.Entity("BusinessObject.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Sub_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Account_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PaymentRef")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("Plan_id")
                        .HasColumnType("uuid");

                    b.Property<double>("PricePaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Sub_id");

                    b.HasIndex("Account_id");

                    b.HasIndex("Plan_id");

                    b.ToTable("Subscription");
                });

            modelBuilder.Entity("BusinessObject.Entities.UserCondition", b =>
                {
                    b.Property<Guid>("UC_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Account_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Condition_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DiagnosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("UC_id");

                    b.HasIndex("Account_id");

                    b.HasIndex("Condition_id");

                    b.ToTable("UserCondition");
                });

            modelBuilder.Entity("BusinessObject.Entities.UserDietPlan", b =>
                {
                    b.Property<Guid>("UDP_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Account_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Diet_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UDP_id");

                    b.HasIndex("Account_id");

                    b.HasIndex("Diet_id");

                    b.ToTable("UserDietPlan");
                });

            modelBuilder.Entity("BusinessObject.Entities.AffiliateProduct", b =>
                {
                    b.HasOne("BusinessObject.Entities.Ingredient", "Ingredient")
                        .WithMany("AffiliateProducts")
                        .HasForeignKey("Ingredient_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Entities.Partner", "Partner")
                        .WithMany("AffiliateProducts")
                        .HasForeignKey("Partner_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("BusinessObject.Entities.Allergy", b =>
                {
                    b.HasOne("BusinessObject.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("Account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Entities.Ingredient", "Ingredient")
                        .WithMany("Allergy")
                        .HasForeignKey("Ingredient_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("BusinessObject.Entities.BmiLog", b =>
                {
                    b.HasOne("BusinessObject.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("Account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BusinessObject.Entities.Collection", b =>
                {
                    b.HasOne("BusinessObject.Entities.Account", "Account")
                        .WithMany("Collections")
                        .HasForeignKey("Account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BusinessObject.Entities.ConditionDietRecommendation", b =>
                {
                    b.HasOne("BusinessObject.Entities.MedicalCondition", "MedicalCondition")
                        .WithMany()
                        .HasForeignKey("Condition_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Entities.DietPlan", "DietPlan")
                        .WithMany()
                        .HasForeignKey("Diet_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DietPlan");

                    b.Navigation("MedicalCondition");
                });

            modelBuilder.Entity("BusinessObject.Entities.GroceryItem", b =>
                {
                    b.HasOne("BusinessObject.Entities.Ingredient", "Ingredient")
                        .WithMany("GroceryItems")
                        .HasForeignKey("Ingredient_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Entities.GroceryList", "GroceryList")
                        .WithMany("GroceryItems")
                        .HasForeignKey("List_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Entities.AffiliateProduct", "AffiliateProduct")
                        .WithMany("GroceryItems")
                        .HasForeignKey("Product_id");

                    b.Navigation("AffiliateProduct");

                    b.Navigation("GroceryList");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("BusinessObject.Entities.GroceryList", b =>
                {
                    b.HasOne("BusinessObject.Entities.Account", "Account")
                        .WithMany("GroceryLists")
                        .HasForeignKey("Account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BusinessObject.Entities.HealthProfile", b =>
                {
                    b.HasOne("BusinessObject.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("Account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BusinessObject.Entities.IngredientLabel", b =>
                {
                    b.HasOne("BusinessObject.Entities.Ingredient", "Ingredient")
                        .WithMany("IngredientLabels")
                        .HasForeignKey("Ingredient_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Entities.IngredientTag", "Ingredient_tag")
                        .WithMany("IngredientLabels")
                        .HasForeignKey("It_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Ingredient_tag");
                });

            modelBuilder.Entity("BusinessObject.Entities.MealPlan", b =>
                {
                    b.HasOne("BusinessObject.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("Account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BusinessObject.Entities.MealPlanDay", b =>
                {
                    b.HasOne("BusinessObject.Entities.MealPlan", "MealPlan")
                        .WithMany("Days")
                        .HasForeignKey("MealPlan_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealPlan");
                });

            modelBuilder.Entity("BusinessObject.Entities.MealPlanEntry", b =>
                {
                    b.HasOne("BusinessObject.Entities.MealPlanDay", "MealPlanDay")
                        .WithMany("Entries")
                        .HasForeignKey("Day_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("Recipe_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealPlanDay");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("BusinessObject.Entities.NutritionGoal", b =>
                {
                    b.HasOne("BusinessObject.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("Account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BusinessObject.Entities.NutritionLog", b =>
                {
                    b.HasOne("BusinessObject.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("Account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("Ingredient_id");

                    b.HasOne("BusinessObject.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("Recipe_id");

                    b.Navigation("Account");

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("BusinessObject.Entities.NutritionalValue", b =>
                {
                    b.HasOne("BusinessObject.Entities.Ingredient", "Ingredient")
                        .WithOne("Nutritional_value")
                        .HasForeignKey("BusinessObject.Entities.NutritionalValue", "Ingredient_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("BusinessObject.Entities.Pantry", b =>
                {
                    b.HasOne("BusinessObject.Entities.Account", "Account")
                        .WithMany("Pantries")
                        .HasForeignKey("Account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Entities.Ingredient", "Ingredient")
                        .WithMany("Pantries")
                        .HasForeignKey("Ingredient_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("BusinessObject.Entities.Recipe", b =>
                {
                    b.HasOne("BusinessObject.Entities.Account", "Account")
                        .WithMany("Recipes")
                        .HasForeignKey("Account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BusinessObject.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("BusinessObject.Entities.Ingredient", "Ingredient")
                        .WithMany("Recipe_Ingredients")
                        .HasForeignKey("Ingredient_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Entities.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("Recipe_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("BusinessObject.Entities.RecipeLabel", b =>
                {
                    b.HasOne("BusinessObject.Entities.Recipe", "Recipe")
                        .WithMany("RecipeLabels")
                        .HasForeignKey("Recipe_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Entities.RecipeTag", "RecipeTag")
                        .WithMany("RecipeLabels")
                        .HasForeignKey("Rt_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("RecipeTag");
                });

            modelBuilder.Entity("BusinessObject.Entities.SavedRecipe", b =>
                {
                    b.HasOne("BusinessObject.Entities.Account", null)
                        .WithMany("SavedRecipes")
                        .HasForeignKey("Account_id");

                    b.HasOne("BusinessObject.Entities.Collection", "Collection")
                        .WithMany("SavedRecipes")
                        .HasForeignKey("Collection_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Entities.Recipe", "Recipe")
                        .WithMany("SavedRecipes")
                        .HasForeignKey("Recipe_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("BusinessObject.Entities.Subscription", b =>
                {
                    b.HasOne("BusinessObject.Entities.Account", "Account")
                        .WithMany("Subscriptions")
                        .HasForeignKey("Account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Entities.Plan", "Plan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("Plan_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("BusinessObject.Entities.UserCondition", b =>
                {
                    b.HasOne("BusinessObject.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("Account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Entities.MedicalCondition", "MedicalCondition")
                        .WithMany()
                        .HasForeignKey("Condition_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("MedicalCondition");
                });

            modelBuilder.Entity("BusinessObject.Entities.UserDietPlan", b =>
                {
                    b.HasOne("BusinessObject.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("Account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Entities.DietPlan", "DietPlan")
                        .WithMany()
                        .HasForeignKey("Diet_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("DietPlan");
                });

            modelBuilder.Entity("BusinessObject.Entities.Account", b =>
                {
                    b.Navigation("Collections");

                    b.Navigation("GroceryLists");

                    b.Navigation("Pantries");

                    b.Navigation("Recipes");

                    b.Navigation("SavedRecipes");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("BusinessObject.Entities.AffiliateProduct", b =>
                {
                    b.Navigation("GroceryItems");
                });

            modelBuilder.Entity("BusinessObject.Entities.Collection", b =>
                {
                    b.Navigation("SavedRecipes");
                });

            modelBuilder.Entity("BusinessObject.Entities.GroceryList", b =>
                {
                    b.Navigation("GroceryItems");
                });

            modelBuilder.Entity("BusinessObject.Entities.Ingredient", b =>
                {
                    b.Navigation("AffiliateProducts");

                    b.Navigation("Allergy");

                    b.Navigation("GroceryItems");

                    b.Navigation("IngredientLabels");

                    b.Navigation("Nutritional_value")
                        .IsRequired();

                    b.Navigation("Pantries");

                    b.Navigation("Recipe_Ingredients");
                });

            modelBuilder.Entity("BusinessObject.Entities.IngredientTag", b =>
                {
                    b.Navigation("IngredientLabels");
                });

            modelBuilder.Entity("BusinessObject.Entities.MealPlan", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("BusinessObject.Entities.MealPlanDay", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("BusinessObject.Entities.Partner", b =>
                {
                    b.Navigation("AffiliateProducts");
                });

            modelBuilder.Entity("BusinessObject.Entities.Plan", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("BusinessObject.Entities.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");

                    b.Navigation("RecipeLabels");

                    b.Navigation("SavedRecipes");
                });

            modelBuilder.Entity("BusinessObject.Entities.RecipeTag", b =>
                {
                    b.Navigation("RecipeLabels");
                });
#pragma warning restore 612, 618
        }
    }
}
