apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smartmeal-api-secret
  labels:
    app.kubernetes.io/name: smartmeal-api
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: smartmeal-secret-store
    kind: ClusterSecretStore
  target:
    name: smartmeal-api-secret
    creationPolicy: Owner
  data:
    - secretKey: ConnectionStrings__DefaultConnection
      remoteRef:
        key: SMARTMEAL_DATABASE_URL
    - secretKey: Jwt__Key
      remoteRef:
        key: SMARTMEAL_JWT_KEY
    - secretKey: Jwt__Issuer
      remoteRef:
        key: SMARTMEAL_JWT_ISSUER
    - secretKey: Jwt__Audience
      remoteRef:
        key: SMARTMEAL_JWT_AUDIENCE
    - secretKey: Google__ClientId
      remoteRef:
        key: SMARTMEAL_GOOGLE_CLIENTID
    - secretKey: Email__SendGridApiKey
      remoteRef:
        key: SMARTMEAL_SENDGRID_API_KEY
    - secretKey: Email__EmailUser
      remoteRef:
        key: SMARTMEAL_EMAIL_USER
    - secretKey: Cloudinary__CloudName
      remoteRef:
        key: SMARTMEAL_CLOUDINARY_CLOUD_NAME
    - secretKey: Cloudinary__ApiKey
      remoteRef:
        key: SMARTMEAL_CLOUDINARY_API_KEY
    - secretKey: Cloudinary__ApiSecret
      remoteRef:
        key: SMARTMEAL_CLOUDINARY_API_SECRET
    - secretKey: PayOS__ClientId
      remoteRef:
        key: SMARTMEAL_PAYOS_CLIENT_ID
    - secretKey: PayOS__ApiKey
      remoteRef:
        key: SMARTMEAL_PAYOS_API_KEY
    - secretKey: PayOS__ChecksumKey
      remoteRef:
        key: SMARTMEAL_PAYOS_CHECKSUM_KEY